-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.InputObject exposing (..)

import Backend.Enum.TeamRole
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildAddTeamMembersInput :
    AddTeamMembersInputRequiredFields
    -> AddTeamMembersInput
buildAddTeamMembersInput required____ =
    { teamId = required____.teamId, userIds = required____.userIds }


type alias AddTeamMembersInputRequiredFields =
    { teamId : Backend.ScalarCodecs.Uuid
    , userIds : List Backend.ScalarCodecs.Uuid
    }


{-| Type for the AddTeamMembersInput input object.
-}
type alias AddTeamMembersInput =
    { teamId : Backend.ScalarCodecs.Uuid
    , userIds : List Backend.ScalarCodecs.Uuid
    }


{-| Encode a AddTeamMembersInput into a value that can be used as an argument.
-}
encodeAddTeamMembersInput : AddTeamMembersInput -> Value
encodeAddTeamMembersInput input____ =
    Encode.maybeObject
        [ ( "teamId", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) input____.teamId |> Just ), ( "userIds", ((Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) |> Encode.list) input____.userIds |> Just ) ]


buildAddTeamOwnersInput :
    AddTeamOwnersInputRequiredFields
    -> AddTeamOwnersInput
buildAddTeamOwnersInput required____ =
    { teamId = required____.teamId, userIds = required____.userIds }


type alias AddTeamOwnersInputRequiredFields =
    { teamId : Backend.ScalarCodecs.Uuid
    , userIds : List Backend.ScalarCodecs.Uuid
    }


{-| Type for the AddTeamOwnersInput input object.
-}
type alias AddTeamOwnersInput =
    { teamId : Backend.ScalarCodecs.Uuid
    , userIds : List Backend.ScalarCodecs.Uuid
    }


{-| Encode a AddTeamOwnersInput into a value that can be used as an argument.
-}
encodeAddTeamOwnersInput : AddTeamOwnersInput -> Value
encodeAddTeamOwnersInput input____ =
    Encode.maybeObject
        [ ( "teamId", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) input____.teamId |> Just ), ( "userIds", ((Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) |> Encode.list) input____.userIds |> Just ) ]


buildCreateTeamInput :
    CreateTeamInputRequiredFields
    -> CreateTeamInput
buildCreateTeamInput required____ =
    { slug = required____.slug, name = required____.name, purpose = required____.purpose }


type alias CreateTeamInputRequiredFields =
    { slug : Backend.ScalarCodecs.Slug
    , name : String
    , purpose : String
    }


{-| Type for the CreateTeamInput input object.
-}
type alias CreateTeamInput =
    { slug : Backend.ScalarCodecs.Slug
    , name : String
    , purpose : String
    }


{-| Encode a CreateTeamInput into a value that can be used as an argument.
-}
encodeCreateTeamInput : CreateTeamInput -> Value
encodeCreateTeamInput input____ =
    Encode.maybeObject
        [ ( "slug", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecSlug) input____.slug |> Just ), ( "name", Encode.string input____.name |> Just ), ( "purpose", Encode.string input____.purpose |> Just ) ]


buildReconcilerConfigInput :
    ReconcilerConfigInputRequiredFields
    -> ReconcilerConfigInput
buildReconcilerConfigInput required____ =
    { key = required____.key, value = required____.value }


type alias ReconcilerConfigInputRequiredFields =
    { key : Backend.ScalarCodecs.ReconcilerConfigKey
    , value : String
    }


{-| Type for the ReconcilerConfigInput input object.
-}
type alias ReconcilerConfigInput =
    { key : Backend.ScalarCodecs.ReconcilerConfigKey
    , value : String
    }


{-| Encode a ReconcilerConfigInput into a value that can be used as an argument.
-}
encodeReconcilerConfigInput : ReconcilerConfigInput -> Value
encodeReconcilerConfigInput input____ =
    Encode.maybeObject
        [ ( "key", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecReconcilerConfigKey) input____.key |> Just ), ( "value", Encode.string input____.value |> Just ) ]


buildRemoveUsersFromTeamInput :
    RemoveUsersFromTeamInputRequiredFields
    -> RemoveUsersFromTeamInput
buildRemoveUsersFromTeamInput required____ =
    { userIds = required____.userIds, teamId = required____.teamId }


type alias RemoveUsersFromTeamInputRequiredFields =
    { userIds : List Backend.ScalarCodecs.Uuid
    , teamId : Backend.ScalarCodecs.Uuid
    }


{-| Type for the RemoveUsersFromTeamInput input object.
-}
type alias RemoveUsersFromTeamInput =
    { userIds : List Backend.ScalarCodecs.Uuid
    , teamId : Backend.ScalarCodecs.Uuid
    }


{-| Encode a RemoveUsersFromTeamInput into a value that can be used as an argument.
-}
encodeRemoveUsersFromTeamInput : RemoveUsersFromTeamInput -> Value
encodeRemoveUsersFromTeamInput input____ =
    Encode.maybeObject
        [ ( "userIds", ((Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) |> Encode.list) input____.userIds |> Just ), ( "teamId", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) input____.teamId |> Just ) ]


buildSetTeamMemberRoleInput :
    SetTeamMemberRoleInputRequiredFields
    -> SetTeamMemberRoleInput
buildSetTeamMemberRoleInput required____ =
    { teamId = required____.teamId, userId = required____.userId, role = required____.role }


type alias SetTeamMemberRoleInputRequiredFields =
    { teamId : Backend.ScalarCodecs.Uuid
    , userId : Backend.ScalarCodecs.Uuid
    , role : Backend.Enum.TeamRole.TeamRole
    }


{-| Type for the SetTeamMemberRoleInput input object.
-}
type alias SetTeamMemberRoleInput =
    { teamId : Backend.ScalarCodecs.Uuid
    , userId : Backend.ScalarCodecs.Uuid
    , role : Backend.Enum.TeamRole.TeamRole
    }


{-| Encode a SetTeamMemberRoleInput into a value that can be used as an argument.
-}
encodeSetTeamMemberRoleInput : SetTeamMemberRoleInput -> Value
encodeSetTeamMemberRoleInput input____ =
    Encode.maybeObject
        [ ( "teamId", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) input____.teamId |> Just ), ( "userId", (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapEncoder .codecUuid) input____.userId |> Just ), ( "role", Encode.enum Backend.Enum.TeamRole.toString input____.role |> Just ) ]


buildUpdateTeamInput :
    (UpdateTeamInputOptionalFields -> UpdateTeamInputOptionalFields)
    -> UpdateTeamInput
buildUpdateTeamInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { name = Absent, purpose = Absent }
    in
    { name = optionals____.name, purpose = optionals____.purpose }


type alias UpdateTeamInputOptionalFields =
    { name : OptionalArgument String
    , purpose : OptionalArgument String
    }


{-| Type for the UpdateTeamInput input object.
-}
type alias UpdateTeamInput =
    { name : OptionalArgument String
    , purpose : OptionalArgument String
    }


{-| Encode a UpdateTeamInput into a value that can be used as an argument.
-}
encodeUpdateTeamInput : UpdateTeamInput -> Value
encodeUpdateTeamInput input____ =
    Encode.maybeObject
        [ ( "name", Encode.string |> Encode.optional input____.name ), ( "purpose", Encode.string |> Encode.optional input____.purpose ) ]
