-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object exposing (..)


type AuditLog
    = AuditLog


type Reconciler
    = Reconciler


type ReconcilerConfig
    = ReconcilerConfig


type Role
    = Role


type ServiceAccount
    = ServiceAccount


type SyncError
    = SyncError


type Team
    = Team


type TeamMember
    = TeamMember


type TeamMembership
    = TeamMembership


type TeamSync
    = TeamSync


type User
    = User
