-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object exposing (..)


type AuditLog
    = AuditLog


type Role
    = Role


type Team
    = Team


type TeamMember
    = TeamMember


type TeamSync
    = TeamSync


type User
    = User


type UserTeam
    = UserTeam
