-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object exposing (..)


type AuditLog
    = AuditLog


type GcpProject
    = GcpProject


type GitHubRepository
    = GitHubRepository


type GitHubRepositoryPermission
    = GitHubRepositoryPermission


type NaisNamespace
    = NaisNamespace


type Reconciler
    = Reconciler


type ReconcilerConfig
    = ReconcilerConfig


type ReconcilerState
    = ReconcilerState


type Role
    = Role


type ServiceAccount
    = ServiceAccount


type SlackAlertsChannel
    = SlackAlertsChannel


type SyncError
    = SyncError


type Team
    = Team


type TeamDeleteKey
    = TeamDeleteKey


type TeamMember
    = TeamMember


type TeamMembership
    = TeamMembership


type TeamSync
    = TeamSync


type User
    = User


type UserSyncRun
    = UserSyncRun
