-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.ScalarCodecs exposing (..)

import Backend.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias AuditAction =
    Backend.Scalar.AuditAction


type alias Id =
    Backend.Scalar.Id


type alias Map =
    Backend.Scalar.Map


type alias ReconcilerName =
    Backend.Scalar.ReconcilerName


type alias RoleName =
    Backend.Scalar.RoleName


type alias Slug =
    Backend.Scalar.Slug


type alias SystemName =
    Backend.Scalar.SystemName


type alias Time =
    Backend.Scalar.Time


type alias Uuid =
    Backend.Scalar.Uuid


codecs : Backend.Scalar.Codecs AuditAction Id Map ReconcilerName RoleName Slug SystemName Time Uuid
codecs =
    Backend.Scalar.defineCodecs
        { codecAuditAction = defaultCodecs.codecAuditAction
        , codecId = defaultCodecs.codecId
        , codecMap = defaultCodecs.codecMap
        , codecReconcilerName = defaultCodecs.codecReconcilerName
        , codecRoleName = defaultCodecs.codecRoleName
        , codecSlug = defaultCodecs.codecSlug
        , codecSystemName = defaultCodecs.codecSystemName
        , codecTime = defaultCodecs.codecTime
        , codecUuid = defaultCodecs.codecUuid
        }
