-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.GitHubRepository exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Name of the repository, with the org prefix.
-}
name : SelectionSet String Backend.Object.GitHubRepository
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| A list of permissions given to the team for this repository.
-}
permissions :
    SelectionSet decodesTo Backend.Object.GitHubRepositoryPermission
    -> SelectionSet (List decodesTo) Backend.Object.GitHubRepository
permissions object____ =
    Object.selectionForCompositeField "permissions" [] object____ (Basics.identity >> Decode.list)


{-| Whether or not the repository is archived.
-}
archived : SelectionSet Bool Backend.Object.GitHubRepository
archived =
    Object.selectionForField "Bool" "archived" [] Decode.bool
