-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.ReconcilerState exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The GitHub team slug.
-}
gitHubTeamSlug : SelectionSet (Maybe Backend.ScalarCodecs.Slug) Backend.Object.ReconcilerState
gitHubTeamSlug =
    Object.selectionForField "(Maybe ScalarCodecs.Slug)" "gitHubTeamSlug" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecSlug |> .decoder |> Decode.nullable)


{-| The Google Workspace group email.
-}
googleWorkspaceGroupEmail : SelectionSet (Maybe String) Backend.Object.ReconcilerState
googleWorkspaceGroupEmail =
    Object.selectionForField "(Maybe String)" "googleWorkspaceGroupEmail" [] (Decode.string |> Decode.nullable)


{-| A list of GCP projects.
-}
gcpProjects :
    SelectionSet decodesTo Backend.Object.GcpProject
    -> SelectionSet (List decodesTo) Backend.Object.ReconcilerState
gcpProjects object____ =
    Object.selectionForCompositeField "gcpProjects" [] object____ (Basics.identity >> Decode.list)


{-| A list of NAIS namespaces.
-}
naisNamespaces :
    SelectionSet decodesTo Backend.Object.NaisNamespace
    -> SelectionSet (List decodesTo) Backend.Object.ReconcilerState
naisNamespaces object____ =
    Object.selectionForCompositeField "naisNamespaces" [] object____ (Basics.identity >> Decode.list)
