-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.Role exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Name of the role.
-}
name : SelectionSet String Backend.Object.Role
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| Whether or not the role is global.
-}
isGlobal : SelectionSet Bool Backend.Object.Role
isGlobal =
    Object.selectionForField "Bool" "isGlobal" [] Decode.bool


{-| Optional target of the role binding.
-}
targetId : SelectionSet (Maybe Backend.ScalarCodecs.Uuid) Backend.Object.Role
targetId =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "targetId" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)
