-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.Role exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Name of the role.
-}
name : SelectionSet Backend.ScalarCodecs.RoleName Backend.Object.Role
name =
    Object.selectionForField "ScalarCodecs.RoleName" "name" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecRoleName |> .decoder)


{-| Whether or not the role is global.
-}
isGlobal : SelectionSet Bool Backend.Object.Role
isGlobal =
    Object.selectionForField "Bool" "isGlobal" [] Decode.bool


{-| Optional service account ID if the role binding targets a service account.
-}
targetServiceAccountID : SelectionSet (Maybe Backend.ScalarCodecs.Uuid) Backend.Object.Role
targetServiceAccountID =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "targetServiceAccountID" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


{-| Optional team slug if the role binding targets a team.
-}
targetTeamSlug : SelectionSet (Maybe Backend.ScalarCodecs.Slug) Backend.Object.Role
targetTeamSlug =
    Object.selectionForField "(Maybe ScalarCodecs.Slug)" "targetTeamSlug" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecSlug |> .decoder |> Decode.nullable)
