-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.SyncError exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Creation time of the error.
-}
createdAt : SelectionSet Backend.ScalarCodecs.Time Backend.Object.SyncError
createdAt =
    Object.selectionForField "ScalarCodecs.Time" "createdAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder)


{-| The name of the reconciler.
-}
reconciler : SelectionSet Backend.ScalarCodecs.ReconcilerName Backend.Object.SyncError
reconciler =
    Object.selectionForField "ScalarCodecs.ReconcilerName" "reconciler" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecReconcilerName |> .decoder)


{-| Error message.
-}
error : SelectionSet String Backend.Object.SyncError
error =
    Object.selectionForField "String" "error" [] Decode.string
