-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.SyncError exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Creation time of the error.
-}
createdAt : SelectionSet Backend.ScalarCodecs.Time Backend.Object.SyncError
createdAt =
    Object.selectionForField "ScalarCodecs.Time" "createdAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder)


{-| The name of the third party system as configured by Console.
-}
system : SelectionSet Backend.ScalarCodecs.SystemName Backend.Object.SyncError
system =
    Object.selectionForField "ScalarCodecs.SystemName" "system" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecSystemName |> .decoder)


{-| Error message.
-}
error : SelectionSet String Backend.Object.SyncError
error =
    Object.selectionForField "String" "error" [] Decode.string
