-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.TeamDeleteKey exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The unique key used to confirm the deletion of a team.
-}
key : SelectionSet Backend.ScalarCodecs.Uuid Backend.Object.TeamDeleteKey
key =
    Object.selectionForField "ScalarCodecs.Uuid" "key" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| The creation timestamp of the key.
-}
createdAt : SelectionSet Backend.ScalarCodecs.Time Backend.Object.TeamDeleteKey
createdAt =
    Object.selectionForField "ScalarCodecs.Time" "createdAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder)


{-| Expiration timestamp of the key.
-}
expires : SelectionSet Backend.ScalarCodecs.Time Backend.Object.TeamDeleteKey
expires =
    Object.selectionForField "ScalarCodecs.Time" "expires" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder)


{-| The user who created the key.
-}
createdBy :
    SelectionSet decodesTo Backend.Object.User
    -> SelectionSet decodesTo Backend.Object.TeamDeleteKey
createdBy object____ =
    Object.selectionForCompositeField "createdBy" [] object____ Basics.identity


{-| The team the delete key is for.
-}
team :
    SelectionSet decodesTo Backend.Object.Team
    -> SelectionSet decodesTo Backend.Object.TeamDeleteKey
team object____ =
    Object.selectionForCompositeField "team" [] object____ Basics.identity
