-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.TeamDeleteKey exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The unique key used to confirm the deletion of a team.
-}
key : SelectionSet Backend.ScalarCodecs.Uuid Backend.Object.TeamDeleteKey
key =
    Object.selectionForField "ScalarCodecs.Uuid" "key" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| Expiration timestamp of the key.
-}
expires : SelectionSet Backend.ScalarCodecs.Time Backend.Object.TeamDeleteKey
expires =
    Object.selectionForField "ScalarCodecs.Time" "expires" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder)
