-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.TeamMetadata exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Metadata key.
-}
key : SelectionSet String Backend.Object.TeamMetadata
key =
    Object.selectionForField "String" "key" [] Decode.string


{-| Metadata value.
-}
value : SelectionSet (Maybe String) Backend.Object.TeamMetadata
value =
    Object.selectionForField "(Maybe String)" "value" [] (Decode.string |> Decode.nullable)
