-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.TeamMemberReconciler exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The reconciler.
-}
reconciler :
    SelectionSet decodesTo Backend.Object.Reconciler
    -> SelectionSet decodesTo Backend.Object.TeamMemberReconciler
reconciler object____ =
    Object.selectionForCompositeField "reconciler" [] object____ Basics.identity


{-| Whether or not the reconciler is enabled for the team member.
-}
enabled : SelectionSet Bool Backend.Object.TeamMemberReconciler
enabled =
    Object.selectionForField "Bool" "enabled" [] Decode.bool
