-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.TeamMember exposing (..)

import Backend.Enum.TeamRole
import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Team instance.
-}
team :
    SelectionSet decodesTo Backend.Object.Team
    -> SelectionSet decodesTo Backend.Object.TeamMember
team object____ =
    Object.selectionForCompositeField "team" [] object____ Basics.identity


{-| User instance.
-}
user :
    SelectionSet decodesTo Backend.Object.User
    -> SelectionSet decodesTo Backend.Object.TeamMember
user object____ =
    Object.selectionForCompositeField "user" [] object____ Basics.identity


{-| The role that the user has in the team.
-}
role : SelectionSet Backend.Enum.TeamRole.TeamRole Backend.Object.TeamMember
role =
    Object.selectionForField "Enum.TeamRole.TeamRole" "role" [] Backend.Enum.TeamRole.decoder


{-| Reconcilers for this member in this team.
-}
reconcilers :
    SelectionSet decodesTo Backend.Object.TeamMemberReconciler
    -> SelectionSet (List decodesTo) Backend.Object.TeamMember
reconcilers object____ =
    Object.selectionForCompositeField "reconcilers" [] object____ (Basics.identity >> Decode.list)
