-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.UserTeam exposing (..)

import Backend.Enum.TeamRole
import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Team instance.
-}
team :
    SelectionSet decodesTo Backend.Object.Team
    -> SelectionSet decodesTo Backend.Object.UserTeam
team object____ =
    Object.selectionForCompositeField "team" [] object____ Basics.identity


{-| The role that the user has in the team.
-}
role : SelectionSet Backend.Enum.TeamRole.TeamRole Backend.Object.UserTeam
role =
    Object.selectionForField "Enum.TeamRole.TeamRole" "role" [] Backend.Enum.TeamRole.decoder
