-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.UserSyncRun exposing (..)

import Backend.Enum.UserSyncRunStatus
import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The correlation ID of the sync run.
-}
correlationID : SelectionSet Backend.ScalarCodecs.Uuid Backend.Object.UserSyncRun
correlationID =
    Object.selectionForField "ScalarCodecs.Uuid" "correlationID" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| Timestamp of when the run started.
-}
startedAt : SelectionSet Backend.ScalarCodecs.Time Backend.Object.UserSyncRun
startedAt =
    Object.selectionForField "ScalarCodecs.Time" "startedAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder)


{-| Timestamp of when the run finished.
-}
finishedAt : SelectionSet (Maybe Backend.ScalarCodecs.Time) Backend.Object.UserSyncRun
finishedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Time)" "finishedAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecTime |> .decoder |> Decode.nullable)


{-| Log entries for the sync run.
-}
logEntries :
    SelectionSet decodesTo Backend.Object.AuditLog
    -> SelectionSet (List decodesTo) Backend.Object.UserSyncRun
logEntries object____ =
    Object.selectionForCompositeField "logEntries" [] object____ (Basics.identity >> Decode.list)


{-| The status of the sync run.
-}
status : SelectionSet Backend.Enum.UserSyncRunStatus.UserSyncRunStatus Backend.Object.UserSyncRun
status =
    Object.selectionForField "Enum.UserSyncRunStatus.UserSyncRunStatus" "status" [] Backend.Enum.UserSyncRunStatus.decoder


{-| Optional error.
-}
error : SelectionSet (Maybe String) Backend.Object.UserSyncRun
error =
    Object.selectionForField "(Maybe String)" "error" [] (Decode.string |> Decode.nullable)
