-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module ScalarCodecs exposing (..)

import Backend.Scalar exposing (defaultCodecs)
import Graphql.Codec exposing (Codec)
import Json.Decode as Decode
import Json.Encode as Encode
import Dict exposing (Dict)


type alias AuditAction =
    Backend.Scalar.AuditAction


type alias Id =
    Backend.Scalar.Id


type alias Map =
    Dict String String


type alias ReconcilerName =
    Backend.Scalar.ReconcilerName


type alias RoleName =
    Backend.Scalar.RoleName


type alias Slug =
    Backend.Scalar.Slug


type alias SystemName =
    Backend.Scalar.SystemName


type alias Time =
    Backend.Scalar.Time


type alias Uuid =
    Backend.Scalar.Uuid


codecMap : Codec Map
codecMap =
    { encoder = Encode.dict (\s -> s) Encode.string
    , decoder = Decode.dict Decode.string
    }


codecs : Backend.Scalar.Codecs AuditAction Id Map ReconcilerName RoleName Slug SystemName Time Uuid
codecs =
    Backend.Scalar.defineCodecs
        { codecAuditAction = defaultCodecs.codecAuditAction
        , codecId = defaultCodecs.codecId
        , codecMap = codecMap
        , codecReconcilerName = defaultCodecs.codecReconcilerName
        , codecRoleName = defaultCodecs.codecRoleName
        , codecSlug = defaultCodecs.codecSlug
        , codecSystemName = defaultCodecs.codecSystemName
        , codecTime = defaultCodecs.codecTime
        , codecUuid = defaultCodecs.codecUuid
        }
